lib/fourty_web/router.ex
defmodule FourtyWeb.Router do
  use FourtyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {FourtyWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :admin_only do
    plug Fourty.Users.AdminOnly
  end

  pipeline :auth_opt do
    plug Fourty.Users.Pipeline
  end

  pipeline :auth_req do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FourtyWeb do
    pipe_through [:browser]
    get "/", SessionController, :index
  end

  scope "/auth", FourtyWeb do
    pipe_through [:browser, :auth_opt]

    get "/:provider", SessionController, :request
    get "/:provider/callback", SessionController, :callback
    post "/:provider/callback", SessionController, :callback
    delete "/logout", SessionController, :logout
  end

  scope "/", FourtyWeb, assigns: %{adm_only: true} do
    pipe_through [:browser, :auth_opt, :auth_req, :admin_only]

    resources "/users", UserController
    resources "/clients", ClientController
    resources "/projects", ProjectController, except: [:new]
    get "/projects/client/:client_id/new", ProjectController, :new
    get "/projects/client/:client_id", ProjectController, :index_client
    resources "/orders", OrderController, except: [:new]
    get "/orders/project/:project_id/new", OrderController, :new
    get "/orders/project/:project_id", OrderController, :index_project
    get "/orders/client/:client_id", OrderController, :index_client
    get "/orders/account/:account_id", OrderController, :index_account
    resources "/accounts", AccountController, except: [:new]
    get "/accounts/project/:project_id/new", AccountController, :new
    get "/accounts/project/:project_id", AccountController, :index_project
    get "/accounts/client/:client_id", AccountController, :index_client
    resources "/dpsts", DepositController, except: [:index]
    get "/dpsts/order/:order_id/new", DepositController, :new_order
    get "/dpsts/account/:account_id", DepositController, :index_account
    get "/dpsts/order/:order_id", DepositController, :index_order
    resources "/wdrws", WithdrawalController, except: [:index]
    get "/wdrws/account/:account_id", WithdrawalController, :index_account
    #
    resources "/wrktms/user/:user_id", WorkItemController,
      except: [:index, :new], as: :work_item_user
    get "/wrktms/user/:user_id/new/:date_as_of", WorkItemController, :new,
      as: :work_item_user
    get "/wrktms/user/:user_id/date/:date_as_of/flip/:item1/:item2", 
      WorkItemController, :flip, as: :work_item_user
    get "/wrktms/user/:user_id/date/:date_as_of", WorkItemController, :index_date,
      as: :work_item_user
    get "/wrktms/user/:user_id/account/:account_id", WorkItemController, :index_account,
      as: :work_item_user
  end

  scope "/", FourtyWeb, assigns: %{adm_only: false} do
    pipe_through [:browser, :auth_opt, :auth_req]

    get "/user/edit", UserController, :edit_pw
    patch "/user/update", UserController, :update_pw
    put "/user/update", UserController, :update_pw

    resources "/wrktms", WorkItemController, except: [:index, :new]
    get "/wrktms/new/:date_as_of", WorkItemController, :new
    get "/wrktms/account/:account_id", WorkItemController, :index_account
    get "/wrktms/date/:date_as_of/flip/:item1/:item2", WorkItemController, :flip
    get "/wrktms/date/:date_as_of", WorkItemController, :index_date
  end

  # Other scopes may use custom stacks.
  # scope "/api", FourtyWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: FourtyWeb.Telemetry
    end
  end

end

lib/fourty/clients/order.ex
defmodule Fourty.Clients.Order do
  @moduledoc """

  The Order schema describes an order for a given project. From a single
  order, you can make one or more deposits to the same or to different
  accounts.

  ## Fields

    - date_eff: the date on which the order becomes effective. This 
    permits you to document the actual placement of the order once you
    received a written confirmation. The field is therefore optional.

    - amount_cur: the amount - in currency units - of the order. For
    example, if the order is of 10,000.00 Euros, amount_cur would be set
    to 1000000.

    - amount_dur: if you want to track the duration spent on a project,
    you can set the amount of time planned to fulfill this order here
    (in internal units of time).

    - label: is a string field which must be used to give the order a
    descriptive name or to document otherwise which order this is.

    - sum_cur: is used internally and holds the accumulated amount of
    money spent for this order.

    - sum_dur: is used internally and holds the accumulated amount of
    time spent for this order.

    - project_id: points to the project for which this order is placed
    for.

  """
  use Ecto.Schema
  import Ecto.Changeset

  schema "orders" do
    field :date_eff, :date
    field :amount_cur, Fourty.TypeCurrency
    field :amount_dur, Fourty.TypeDuration
    field :label, :string
    field :sum_cur, Fourty.TypeCurrency, virtual: true, default: 0
    field :sum_dur, Fourty.TypeDuration, virtual: true, default: 0
    belongs_to :project, Fourty.Clients.Project
    has_many :deposits, Fourty.Accounting.Deposit
    timestamps()
  end

  @doc false
  def changeset(order, attrs) do
    order
    |> cast(attrs, [:date_eff, :amount_cur, :amount_dur, :label, :project_id])
    |> validate_required([:project_id, :label])
    |> assoc_constraint(:project)
  end
end

lib/fourty_web/controllers/order_controller.ex
defmodule FourtyWeb.OrderController do
  use FourtyWeb, :controller

  alias Fourty.Clients
  alias Fourty.Clients.Order

  def index(conn, _params) do
    orders = Clients.list_orders()
    order_sums = Clients.load_all_order_sums()
    heading = dgettext("orders", "index")
    render(conn, "index.html", orders: orders, order_sums: order_sums, heading: heading)
  end

  def index_project(conn, %{"project_id" => project_id}) do
    project = Clients.get_project!(project_id)
    orders = Clients.list_orders(client_id: project.client_id, project_id: project.id)
    order_sums = Clients.load_all_order_sums()

    heading =
      dgettext("orders", "index_project",
        label: List.first(List.first(orders).visible_projects).label
      )

    render(conn, "index.html", orders: orders, order_sums: order_sums, heading: heading)
  end

  def index_client(conn, %{"client_id" => client_id}) do
    orders = Clients.list_orders(client_id: client_id)
    order_sums = Clients.load_all_order_sums()
    heading = dgettext("orders", "index_client", label: List.first(orders).label)
    render(conn, "index.html", orders: orders, order_sums: order_sums, heading: heading)
  end

  def index_account(conn, %{"account_id" => account_id}) do
    account = Fourty.Accounting.get_account_solo!(account_id)
    orders = Clients.list_orders(account_id: account_id)
    order_sums = Clients.load_all_order_sums()

    heading = dgettext("orders", "index_account", label: account.label)
    render(conn, "index.html", orders: orders, order_sums: order_sums, heading: heading)
  end

  def new(conn, params) do
    changeset = Ecto.Changeset.cast(%Order{}, params, [:project_id])

    order =
      Ecto.Changeset.apply_changes(changeset)
      |> Fourty.Repo.preload(project: [:client])

    render(conn, "new.html", order: order, changeset: changeset)
  end

  def create(conn, %{"order" => order_params}) do
    case Clients.create_order(order_params) do
      {:ok, order} ->
        conn
        |> put_flash(:info, dgettext("orders", "create_success"))
        |> redirect(to: Routes.order_path(conn, :show, order))

      {:error, %Ecto.Changeset{} = changeset} ->
        order =
          Ecto.Changeset.apply_changes(changeset)
          |> Fourty.Repo.preload(project: [:client])

        render(conn, "new.html", order: order, changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    order = Clients.get_order!(id)
    render(conn, "show.html", order: order)
  end

  def edit(conn, %{"id" => id}) do
    order = Clients.get_order!(id)
    changeset = Clients.change_order(order)
    render(conn, "edit.html", order: order, changeset: changeset)
  end

  def update(conn, %{"id" => id, "order" => order_params}) do
    order = Clients.get_order!(id)

    case Clients.update_order(order, order_params) do
      {:ok, order} ->
        conn
        |> put_flash(:info, dgettext("orders", "update_success"))
        |> redirect(to: Routes.order_path(conn, :show, order))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", order: order, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    order = Clients.get_order!(id)
    {:ok, _order} = Clients.delete_order(order)

    conn
    |> put_flash(:info, dgettext("orders", "delete_success"))
    |> redirect(to: Routes.order_path(conn, :index))
  end
end

lib/fourty_web/views/order_view.ex
defmodule FourtyWeb.OrderView do
  use FourtyWeb, :view
end

lib/fourty_web/templates/order/edit.html.eex
<h1><%= dgettext("orders", "edit") %></h1>
<div class="row row-cols-auto">
	<div class="col-sm-3 p-3 border bg-light">
		<%= render "form.html", Map.put(assigns, :action, Routes.order_path(@conn, :update, @order)) %>
	</div>
</div>

lib/fourty_web/templates/order/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p><%= dgettext("errors","error_alert") %></p>
    </div>
  <% end %>

  <%= hidden_input(f, :client_id) %>
  <%= my_label("clients", "label") %>
  <%= my_text_link(@order.project.client.label,
      Routes.client_path(@conn, :show, @order.project.client.id)) %><br />

  <%= hidden_input(f, :project_id) %>
  <%= my_label("projects", "label") %>
  <%= my_text_link(@order.project.label,
      Routes.project_path(@conn, :show, @order.project.id)) %><br />

  <%= my_label("orders", "label") %>
  <%= my_longtext_input(f, :label) %><br />
  <%= error_tag(f, :label) %>

  <%= my_label("orders", "date_eff") %>
  <%= my_date_input(f, :date_eff) %><br />
  <%= error_tag(f, :date_eff) %>

  <div class="row align-items-end">
    <div class="col-sm-6">
      <%= my_label("orders", "amount_cur") %>
    </div>
    <div class="col-sm-6">
      <%= my_label("orders", "amount_dur") %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <%= my_currency_input(f, :amount_cur) %>
      <%= error_tag(f, :amount_cur) %>
    </div>
    <div class="col-sm-6">
      <%= my_duration_input(f, :amount_dur) %><br />
      <%= error_tag(f, :amount_dur) %>
    </div>
  </div>

  <%= my_submit() %>
  <%= if id = Ecto.Changeset.get_field(@changeset, :id),
        do: my_back_link(Routes.order_path(@conn, :show, id )),
        else: my_back_link(Routes.order_path(@conn, :index)) %>
<% end %>

lib/fourty_web/templates/order/index.html.eex
<h1><%= @heading %></h1>
<div class="row row-cols-auto">
  <div class="table-responsive col-sm-10 p3 border bg-light">
    <table class="table table-hover">
      <thead>
        <tr>
          <th class="col-sm-2">&nbsp;</th>
          <th class="col-sm-1">&nbsp;</th>
          <th colspan="2" class="col-sm-2 text-center">Ordered&nbsp;/&nbsp;Booked&nbsp;/&nbsp;Available</th>
          <th class="col-sm-3">&nbsp;</th>
        </tr>
        <tr>
          <th class="col-sm-2"><%= dgettext("orders", "label") %></th>
          <th class="col-sm-1"><%= dgettext("orders", "date_eff") %></th>
          <th class="col-sm-1 text-end"><%= dgettext("orders", "amount_cur") %></th>
          <th class="col-sm-1 text-end"><%= dgettext("orders", "amount_dur") %></th>
          <th class="col-sm-3"><%= dgettext("global","actions") %></th>
        </tr>
      </thead>
      <tbody>
        <%= for client <- @orders do %>
        <tr>
          <td colspan="4">
            <%= dgettext("clients", "label") %>&nbsp;:&nbsp;
            <strong>
              <%= link client.label, to: Routes.client_path(@conn, :show, client.id) %>
            </strong>
          </td>
          <td>
            &nbsp;
          </td>
        </tr>
        <%= for project <- client.visible_projects do %>
          <tr>
            <td class="indent-1" colspan="4">
              <%= dgettext("projects", "label") %>&nbsp;:&nbsp;
              <strong>
                <%= link project.label, to: Routes.project_path(@conn, :show, project.id) %>
              </strong>
            </td>
            <td>
              <%= my_action_link("orders","new", Routes.order_path(@conn, :new, project.id)) %>
            </td>
          </tr>
          <%= for order <- project.orders do %>
          <% order = Map.merge(order, Fourty.Clients.get_order_sums(@order_sums, order.id)) %>
          <tr>
            <td class="indent-2"><%= order.label %></td>
            <td><%= order.date_eff %></td>
            <td class="text-end">
              <%= int2cur(order.amount_cur) %><br />
              <%= "-" <> int2cur(order.sum_cur || 0) %><br />
              <%= int2cur(delta(order.amount_cur, order.sum_cur) || 0) %></td>
            <td class="text-end">
              <%= min2dur(order.amount_dur) %><br />
              <%= "-" <> min2dur(order.sum_dur || 0) %><br />
              <%= min2dur(delta(order.amount_dur, order.sum_dur) || 0) %></td>
            <td>
              <%= my_action_link("global", "show", Routes.order_path(@conn, :show, order)) %>
              <%= my_action_link("global", "edit", Routes.order_path(@conn, :edit, order)) %>
              <%= my_action_link("global", "delete", Routes.order_path(@conn, :delete, order)) %>
              <%= my_action_link("deposits", "xfer", Routes.deposit_path(@conn, :new_order, order)) %>
              <%= my_action_link("deposits", "index_order_short", Routes.deposit_path(@conn, :index_order, order)) %>
            </td>
          </tr>
          <% end %>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

lib/fourty_web/templates/order/new.html.eex
<h1><%= dgettext("orders", "new") %></h1>
<div class="row row-cols-auto">
	<div class="col-sm-3 p-3 border bg-light">
		<%= render "form.html", Map.put(assigns, :action, Routes.order_path(@conn, :create)) %>
	</div>
</div>

lib/fourty_web/templates/order/show.html.eex
<h1><%= dgettext("orders","show") %></h1>
<div class="row row-cols-auto">
  <div class="col-sm-3 p-3 border bg-light">

    <%= my_label("clients", "label") %>
    <%= my_text_link(@order.project.client.label,
        Routes.client_path(@conn, :show, @order.project.client.id)) %><br />

    <%= my_label("projects", "label") %>
    <%= my_text_link(@order.project.label,
        Routes.project_path(@conn, :show, @order.project.id)) %><br />

    <%= my_label("orders", "label") %>
    <%= my_longtext_value(@order.label) %><br />

    <%= my_label("orders", "date_eff") %>
    <%= my_date_value(@order.date_eff) %><br />

    <div class="row align-items-end">
        <div class="col-sm-6">
            <%= my_label("orders", "amount_cur") %>
        </div>
        <div class="col-sm-6">
            <%= my_label("orders", "amount_dur") %>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <%= my_currency_value(@order.amount_cur) %>
        </div>
        <div class="col-sm-6">
            <%= my_duration_value(@order.amount_dur) %><br />
        </div>
    </div>

    <%= my_action("global", "edit", Routes.order_path(@conn, :edit, @order)) %>
    <%= my_action("orders", "index", Routes.order_path(@conn, :index)) %>
    <%= my_action("deposits", "transfer", Routes.deposit_path(@conn, :new_order, @order.id)) %>
  </div>
</div>