lib/fourty_web/router.ex
defmodule FourtyWeb.Router do
  use FourtyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {FourtyWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :admin_only do
    plug Fourty.Users.AdminOnly
  end

  pipeline :auth_opt do
    plug Fourty.Users.Pipeline
  end

  pipeline :auth_req do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FourtyWeb do
    pipe_through [:browser]
    get "/", SessionController, :index
  end

  scope "/auth", FourtyWeb do
    pipe_through [:browser, :auth_opt]

    get "/:provider", SessionController, :request
    get "/:provider/callback", SessionController, :callback
    post "/:provider/callback", SessionController, :callback
    delete "/logout", SessionController, :logout
  end

  scope "/", FourtyWeb, assigns: %{adm_only: true} do
    pipe_through [:browser, :auth_opt, :auth_req, :admin_only]

    resources "/users", UserController
    resources "/clients", ClientController
    resources "/projects", ProjectController, except: [:new]
    get "/projects/client/:client_id/new", ProjectController, :new
    get "/projects/client/:client_id", ProjectController, :index_client
    resources "/orders", OrderController, except: [:new]
    get "/orders/project/:project_id/new", OrderController, :new
    get "/orders/project/:project_id", OrderController, :index_project
    get "/orders/client/:client_id", OrderController, :index_client
    get "/orders/account/:account_id", OrderController, :index_account
    resources "/accounts", AccountController, except: [:new]
    get "/accounts/project/:project_id/new", AccountController, :new
    get "/accounts/project/:project_id", AccountController, :index_project
    get "/accounts/client/:client_id", AccountController, :index_client
    resources "/dpsts", DepositController, except: [:index]
    get "/dpsts/order/:order_id/new", DepositController, :new_order
    get "/dpsts/account/:account_id", DepositController, :index_account
    get "/dpsts/order/:order_id", DepositController, :index_order
    resources "/wdrws", WithdrawalController, except: [:index]
    get "/wdrws/account/:account_id", WithdrawalController, :index_account
    #
    resources "/wrktms/user/:user_id", WorkItemController,
      except: [:index, :new], as: :work_item_user
    get "/wrktms/user/:user_id/new/:date_as_of", WorkItemController, :new,
      as: :work_item_user
    get "/wrktms/user/:user_id/date/:date_as_of/flip/:item1/:item2", 
      WorkItemController, :flip, as: :work_item_user
    get "/wrktms/user/:user_id/date/:date_as_of", WorkItemController, :index_date,
      as: :work_item_user
    get "/wrktms/user/:user_id/account/:account_id", WorkItemController, :index_account,
      as: :work_item_user
  end

  scope "/", FourtyWeb, assigns: %{adm_only: false} do
    pipe_through [:browser, :auth_opt, :auth_req]

    get "/user/edit", UserController, :edit_pw
    patch "/user/update", UserController, :update_pw
    put "/user/update", UserController, :update_pw

    resources "/wrktms", WorkItemController, except: [:index, :new]
    get "/wrktms/new/:date_as_of", WorkItemController, :new
    get "/wrktms/account/:account_id", WorkItemController, :index_account
    get "/wrktms/date/:date_as_of/flip/:item1/:item2", WorkItemController, :flip
    get "/wrktms/date/:date_as_of", WorkItemController, :index_date
  end

  # Other scopes may use custom stacks.
  # scope "/api", FourtyWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: FourtyWeb.Telemetry
    end
  end

end

lib/fourty_web/views/layout_view.ex
defmodule FourtyWeb.LayoutView do
  use FourtyWeb, :view
end

lib/fourty_web/templates/layout/app.html.eex
<main role="main" class="container">
	<%= unless is_nil( msg = get_flash(@conn, :info)) do %>
    	<p class="alert alert-info" role="alert"><%= msg %></p>
  	<% end %>
  	<%= unless is_nil(msg = get_flash(@conn, :error)) do %>
    	<p class="alert alert-danger" role="alert"><%= msg %></p></p>
  	<% end %>
<%= @inner_content %>
</main>

lib/fourty_web/templates/layout/live.html.leex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/fourty_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <link rel="shortcut icon" type="image/x-icon" href="<%= Routes.static_path(@conn, "/favicon.ico") %>" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Fourty", suffix: " · Phoenix" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Fourty</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent" phx-update="ignore">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownUser" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= user = Plug.Conn.get_session(@conn, :current_user); user && user.username || dgettext("sessions", "user") %></a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownUser">
                  <%= if Plug.Conn.get_session(@conn, :current_user) do %>
                    <li><%= link(dgettext("work_items", "index_today"), to: Routes.work_item_path(@conn, :index_date, "today"), class: "dropdown-item") %></li>
                    <li><%= link(dgettext("sessions", "edit_pw"), to: Routes.user_path(@conn, :edit_pw), class: "dropdown-item") %></li>
                    <li><%= link(dgettext("sessions", "logout"), to: Routes.session_path(@conn, :logout), method: :delete, class: "dropdown-item") %></li>
                  <% else %>
                    <li><%= link(dgettext("sessions", "login"), to: Routes.session_path(@conn, :index), class: "dropdown-item") %></li>
                  <% end %>
                </ul>
              </li>
              <%= user = Plug.Conn.get_session(@conn, :current_user); if user && Fourty.Users.has_role?(user, :admin) do %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAdmin" role="button" data-bs-toggle="dropdown" aria-expanded="false">Admin</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownAdmin">
                  <li><%= link(dgettext("clients","clients"), to: Routes.client_path(@conn, :index), class: "dropdown-item") %></li>
                  <li><%= link(dgettext("projects","projects"), to: Routes.project_path(@conn, :index), class: "dropdown-item") %></li>
                  <li><%= link(dgettext("accounts","accounts"), to: Routes.account_path(@conn, :index), class: "dropdown-item") %></li>
                  <li><%= link(dgettext("orders","orders"), to: Routes.order_path(@conn, :index), class: "dropdown-item") %></li>
                  <li><%= link(dgettext("users","users"), to: Routes.user_path(@conn, :index), class: "dropdown-item") %></li>
                  <!--li><#= link(dgettext("users","rates"), to: Routes.rate_path(@conn, :index), class: "dropdown-item") %></li-->
                  <li><hr class="dropdown-divider"></li>
                  <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
                    <li><%= link("LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "dropdown-item", target: "_blank", rel: "noopener") %></li>
                  <% end %>
                </ul>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= @inner_content %>
  </body>
</html>